t=linspace(-1,5,610)
func = exp(-2 .* t) .* cos(8 .* 22/7 .* t)
subplot(2,1,1)
stem(func)
title("Difference between plot and stem")
xlabel("T sec")
ylabel("F(t)")
subplot(2,1,2)
plot(func)
axis([-3 12 -10 10])
title("Difference between plot and stem")
xlabel("T sec")
ylabel("F(t)") 